[package]
name = "hello_macro"
version = "0.1.0"
edition = "2018"


[lib]
name = "helloMacro"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
